Loading modules...
Running test...
INFO 08-25 13:43:06 [__init__.py:241] Automatically detected platform cuda.
INFO 08-25 13:43:09 [utils.py:326] non-default args: {'model': 'unsloth/phi-4-unsloth-bnb-4bit', 'disable_log_stats': True}
INFO 08-25 13:43:21 [__init__.py:711] Resolved architecture: LlamaForCausalLM
INFO 08-25 13:43:21 [__init__.py:1750] Using max model len 16384
WARNING 08-25 13:43:22 [__init__.py:1171] bitsandbytes quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 08-25 13:43:24 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:25 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:25 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='unsloth/phi-4-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/phi-4-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/phi-4-unsloth-bnb-4bit, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:28 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
[1;36m(EngineCore_0 pid=35227)[0;0m WARNING 08-25 13:43:28 [topk_topp_sampler.py:61] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:28 [gpu_model_runner.py:1953] Starting to load model unsloth/phi-4-unsloth-bnb-4bit...
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:28 [gpu_model_runner.py:1985] Loading model from scratch...
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:32 [cuda.py:328] Using Flash Attention backend on V1 engine.
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:33 [bitsandbytes_loader.py:742] Loading weights with BitsAndBytes quantization. May take a while ...
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:33 [weight_utils.py:296] Using model weights format ['*.safetensors']
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:00<00:00,  4.90it/s]
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:00<00:00,  5.62it/s]
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:00<00:00,  8.21it/s]
[1;36m(EngineCore_0 pid=35227)[0;0m 
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:14<00:29, 14.53s/it]
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:22<00:10, 10.91s/it]
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:24<00:00,  6.67s/it]
[1;36m(EngineCore_0 pid=35227)[0;0m Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:24<00:00,  8.18s/it]
[1;36m(EngineCore_0 pid=35227)[0;0m 
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:43:59 [gpu_model_runner.py:2007] Model loading took 10.2823 GiB and 30.034416 seconds
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:44:32 [backends.py:548] Using cache directory: /lustre/romanistik/leonnial/.cache/vllm/torch_compile_cache/4d34955c76/rank_0_0/backbone for vLLM's torch.compile
[1;36m(EngineCore_0 pid=35227)[0;0m INFO 08-25 13:44:32 [backends.py:559] Dynamo bytecode transform time: 33.17 s
nvc-Error-Unknown switch: -Wno-psabi
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 89, in __init__
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     self._initialize_kv_caches(vllm_config)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 179, in _initialize_kv_caches
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     self.model_executor.determine_available_memory())
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/executor/abstract.py", line 76, in determine_available_memory
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     output = self.collective_rpc("determine_available_memory")
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_worker.py", line 244, in determine_available_memory
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     self.model_runner.profile_run()
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2622, in profile_run
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     = self._dummy_run(self.max_num_tokens, is_profile=True)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2395, in _dummy_run
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     outputs = self.model(
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]               ^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 577, in forward
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     model_output = self.model(input_ids, positions, intermediate_tensors,
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 272, in __call__
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     output = self.compiled_callable(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 663, in _fn
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 760, in _compile_fx_inner
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     raise InductorError(e, currentframe()).with_traceback(
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 745, in _compile_fx_inner
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     mb_compiled_graph = fx_codegen_and_compile(
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]                         ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1295, in fx_codegen_and_compile
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1197, in codegen_and_compile
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     compiled_fn = graph.compile_to_module().call
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/graph.py", line 2083, in compile_to_module
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     return self._compile_to_module()
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/graph.py", line 2130, in _compile_to_module
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     mod = PyCodeCache.load_by_key_path(
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 2747, in load_by_key_path
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     mod = _reload_python_module(key, path)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/compile_tasks.py", line 36, in _reload_python_module
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     exec(code, mod.__dict__, mod.__dict__)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/.cache/vllm/torch_compile_cache/4d34955c76/rank_0_0/inductor_cache/hw/chwrjuwjtqdghsrkzzfjllrzuafngga74x4ffwerbrpybaqlirnh.py", line 60, in <module>
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     triton_red_fused__to_copy_add_embedding_mean_mul_pow_rsqrt_0 = async_compile.triton('triton_red_fused__to_copy_add_embedding_mean_mul_pow_rsqrt_0', '''
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/async_compile.py", line 346, in triton
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     kernel.precompile(warm_cache_only=False)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 277, in precompile
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     self._make_launchers()
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 434, in _make_launchers
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     launchers.append(result.make_launcher())
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]                      ^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 1091, in make_launcher
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     binary._init_handles()
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/compiler/compiler.py", line 397, in _init_handles
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     self.run = driver.active.launcher_cls(self.src, self.metadata)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 516, in __init__
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     mod = compile_module_from_src(src, "__triton_launcher")
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 66, in compile_module_from_src
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/runtime/build.py", line 36, in _build
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     subprocess.check_call(cc_cmd, stdout=subprocess.DEVNULL)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]   File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/subprocess.py", line 413, in check_call
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700]     raise CalledProcessError(retcode, cmd)
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700] torch._inductor.exc.InductorError: CalledProcessError: Command '['/software/nvidia/hpc_sdk/nvhpc_2025_251_Linux_x86_64_cuda_12.6/Linux_x86_64/25.1/compilers/bin/nvc', '/tmp/tmpfg5t_2qp/main.c', '-O3', '-shared', '-fPIC', '-Wno-psabi', '-o', '/tmp/tmpfg5t_2qp/__triton_launcher.cpython-311-x86_64-linux-gnu.so', '-lcuda', '-L/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/lib', '-L/usr/lib64', '-L/usr/lib', '-I/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/include', '-I/tmp/tmpfg5t_2qp', '-I/software/eb/Python/3.11.5-GCCcore-13.2.0/include/python3.11']' returned non-zero exit status 1.
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700] 
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700] Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
[1;36m(EngineCore_0 pid=35227)[0;0m ERROR 08-25 13:44:35 [core.py:700] 
[1;36m(EngineCore_0 pid=35227)[0;0m Process EngineCore_0:
[1;36m(EngineCore_0 pid=35227)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_0 pid=35227)[0;0m     self.run()
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_0 pid=35227)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 704, in run_engine_core
[1;36m(EngineCore_0 pid=35227)[0;0m     raise e
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=35227)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=35227)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 89, in __init__
[1;36m(EngineCore_0 pid=35227)[0;0m     self._initialize_kv_caches(vllm_config)
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 179, in _initialize_kv_caches
[1;36m(EngineCore_0 pid=35227)[0;0m     self.model_executor.determine_available_memory())
[1;36m(EngineCore_0 pid=35227)[0;0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/executor/abstract.py", line 76, in determine_available_memory
[1;36m(EngineCore_0 pid=35227)[0;0m     output = self.collective_rpc("determine_available_memory")
[1;36m(EngineCore_0 pid=35227)[0;0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=35227)[0;0m     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=35227)[0;0m     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=35227)[0;0m     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_worker.py", line 244, in determine_available_memory
[1;36m(EngineCore_0 pid=35227)[0;0m     self.model_runner.profile_run()
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2622, in profile_run
[1;36m(EngineCore_0 pid=35227)[0;0m     = self._dummy_run(self.max_num_tokens, is_profile=True)
[1;36m(EngineCore_0 pid=35227)[0;0m       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=35227)[0;0m     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2395, in _dummy_run
[1;36m(EngineCore_0 pid=35227)[0;0m     outputs = self.model(
[1;36m(EngineCore_0 pid=35227)[0;0m               ^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=35227)[0;0m     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=35227)[0;0m     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 577, in forward
[1;36m(EngineCore_0 pid=35227)[0;0m     model_output = self.model(input_ids, positions, intermediate_tensors,
[1;36m(EngineCore_0 pid=35227)[0;0m                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 272, in __call__
[1;36m(EngineCore_0 pid=35227)[0;0m     output = self.compiled_callable(*args, **kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 663, in _fn
[1;36m(EngineCore_0 pid=35227)[0;0m     raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
[1;36m(EngineCore_0 pid=35227)[0;0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 760, in _compile_fx_inner
[1;36m(EngineCore_0 pid=35227)[0;0m     raise InductorError(e, currentframe()).with_traceback(
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 745, in _compile_fx_inner
[1;36m(EngineCore_0 pid=35227)[0;0m     mb_compiled_graph = fx_codegen_and_compile(
[1;36m(EngineCore_0 pid=35227)[0;0m                         ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1295, in fx_codegen_and_compile
[1;36m(EngineCore_0 pid=35227)[0;0m     return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
[1;36m(EngineCore_0 pid=35227)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1197, in codegen_and_compile
[1;36m(EngineCore_0 pid=35227)[0;0m     compiled_fn = graph.compile_to_module().call
[1;36m(EngineCore_0 pid=35227)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/graph.py", line 2083, in compile_to_module
[1;36m(EngineCore_0 pid=35227)[0;0m     return self._compile_to_module()
[1;36m(EngineCore_0 pid=35227)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/graph.py", line 2130, in _compile_to_module
[1;36m(EngineCore_0 pid=35227)[0;0m     mod = PyCodeCache.load_by_key_path(
[1;36m(EngineCore_0 pid=35227)[0;0m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 2747, in load_by_key_path
[1;36m(EngineCore_0 pid=35227)[0;0m     mod = _reload_python_module(key, path)
[1;36m(EngineCore_0 pid=35227)[0;0m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/compile_tasks.py", line 36, in _reload_python_module
[1;36m(EngineCore_0 pid=35227)[0;0m     exec(code, mod.__dict__, mod.__dict__)
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/.cache/vllm/torch_compile_cache/4d34955c76/rank_0_0/inductor_cache/hw/chwrjuwjtqdghsrkzzfjllrzuafngga74x4ffwerbrpybaqlirnh.py", line 60, in <module>
[1;36m(EngineCore_0 pid=35227)[0;0m     triton_red_fused__to_copy_add_embedding_mean_mul_pow_rsqrt_0 = async_compile.triton('triton_red_fused__to_copy_add_embedding_mean_mul_pow_rsqrt_0', '''
[1;36m(EngineCore_0 pid=35227)[0;0m                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/async_compile.py", line 346, in triton
[1;36m(EngineCore_0 pid=35227)[0;0m     kernel.precompile(warm_cache_only=False)
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 277, in precompile
[1;36m(EngineCore_0 pid=35227)[0;0m     self._make_launchers()
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 434, in _make_launchers
[1;36m(EngineCore_0 pid=35227)[0;0m     launchers.append(result.make_launcher())
[1;36m(EngineCore_0 pid=35227)[0;0m                      ^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 1091, in make_launcher
[1;36m(EngineCore_0 pid=35227)[0;0m     binary._init_handles()
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/compiler/compiler.py", line 397, in _init_handles
[1;36m(EngineCore_0 pid=35227)[0;0m     self.run = driver.active.launcher_cls(self.src, self.metadata)
[1;36m(EngineCore_0 pid=35227)[0;0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 516, in __init__
[1;36m(EngineCore_0 pid=35227)[0;0m     mod = compile_module_from_src(src, "__triton_launcher")
[1;36m(EngineCore_0 pid=35227)[0;0m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 66, in compile_module_from_src
[1;36m(EngineCore_0 pid=35227)[0;0m     so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
[1;36m(EngineCore_0 pid=35227)[0;0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/runtime/build.py", line 36, in _build
[1;36m(EngineCore_0 pid=35227)[0;0m     subprocess.check_call(cc_cmd, stdout=subprocess.DEVNULL)
[1;36m(EngineCore_0 pid=35227)[0;0m   File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/subprocess.py", line 413, in check_call
[1;36m(EngineCore_0 pid=35227)[0;0m     raise CalledProcessError(retcode, cmd)
[1;36m(EngineCore_0 pid=35227)[0;0m torch._inductor.exc.InductorError: CalledProcessError: Command '['/software/nvidia/hpc_sdk/nvhpc_2025_251_Linux_x86_64_cuda_12.6/Linux_x86_64/25.1/compilers/bin/nvc', '/tmp/tmpfg5t_2qp/main.c', '-O3', '-shared', '-fPIC', '-Wno-psabi', '-o', '/tmp/tmpfg5t_2qp/__triton_launcher.cpython-311-x86_64-linux-gnu.so', '-lcuda', '-L/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/lib', '-L/usr/lib64', '-L/usr/lib', '-I/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/triton/backends/nvidia/include', '-I/tmp/tmpfg5t_2qp', '-I/software/eb/Python/3.11.5-GCCcore-13.2.0/include/python3.11']' returned non-zero exit status 1.
[1;36m(EngineCore_0 pid=35227)[0;0m 
[1;36m(EngineCore_0 pid=35227)[0;0m Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
[1;36m(EngineCore_0 pid=35227)[0;0m 
Traceback (most recent call last):
  File "/lustre/romanistik/leonnial/gec_extractor/./src/extract_pipeline/test.py", line 27, in <module>
    main()
  File "/lustre/romanistik/leonnial/gec_extractor/./src/extract_pipeline/test.py", line 14, in main
    llm = LLM(model="unsloth/phi-4-unsloth-bnb-4bit",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 285, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 490, in from_engine_args
    return engine_cls.from_vllm_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 127, in from_vllm_config
    return cls(vllm_config=vllm_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 104, in __init__
    self.engine_core = EngineCoreClient.make_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 80, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 600, in __init__
    super().__init__(
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 446, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 706, in launch_core_engines
    wait_for_engine_startup(
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 759, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
Script finished!
